main: main.cpp glm.cpp mtxlib.cpp trackball.cpp
	g++ main.cpp glm.cpp mtxlib.cpp trackball.cpp -o main -L/System/Library/Frameworks -framework GLUT -framework OpenGL -framework OpenAL -framework AudioToolbox -framework CoreFoundation


clean:
	rm main
